services:
  # Backend API Service
  - type: web
    name: sweet-shop-api
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python start.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sweet-shop-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://sweet-shop-frontend.onrender.com
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false

  # Frontend Service
  - type: web
    name: sweet-shop-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: sweet-shop-api
          property: host

databases:
  - name: sweet-shop-db
    plan: free
    databaseName: sweet_shop
